### ISSUE TITLE
Define the daylighting simulation as a method in the metabase

### ISSUE THREAD

**Issue by christoph-maurer** [ise621/building-envelope-data#144]
This issues is based on #130. Please define the daylight simulation similar to
```
            "method": {
              "id": "473a2f69-2e18-4745-809d-519882b25e8b",
              "reference": {
                "publication": {
                  "identifiers": {
                    "doi": "10.1016/j.solener.2017.05.065"
                  }
                }
              }
            },
```
The demonstration #132 applies this method to the product data of #145.

**Comment by bbuenoun** [comment]
@christoph-maurer What would be an example of [affiliations/items/properties/kind](https://github.com/ise621/building-envelope-data/blob/7706287bb6035eb31536c09b65b917d1025bedb0/schemas/stakeholder.json#L95)? Why is this field compulsory?

**Comment by christoph-maurer** [comment]
> @christoph-maurer What would be an example of [affiliations/items/properties/kind](https://github.com/ise621/building-envelope-data/blob/7706287bb6035eb31536c09b65b917d1025bedb0/schemas/stakeholder.json#L95)? Why is this field compulsory?

@simon-wacker Can you answer Bruno's questions?

**Comment by simon-wacker** [comment]
Actually, no, I can't. We can just make it optional.

**Comment by christoph-maurer** [comment]
I moved this topic to #198 .
