### ISSUE TITLE
Alternative data format for BSDF and other data

### ISSUE THREAD

**Issue by RDmitchell** [ise621/building-envelope-data#178]
IGSDB stores data for the following in XML format, and we propose to pass that data to ICON keeping that format

* BSDF XML representing dual band or 4 band
* THMX XML and genBSDF XML representing shading layer descriptions (cellular shades, pleated shades, etc)

When information about a shading layer is requested from the IGSDB, the appropriate data from these files will be included in the response in the original XML format. 

We can provide schemas for understanding the data in those XML files; may include a reference to schema in the response

**Comment by christoph-maurer** [comment]
We propose to define the 3 XML formats which you mention as dataFormat in the metabase. Each dataFormat is identified by a [formatId](https://github.com/ise621/building-envelope-data/blob/7706287bb6035eb31536c09b65b917d1025bedb0/apis/database.graphql#L1590). The [media type](https://www.iana.org/assignments/media-types/media-types.xhtml) of the 3 formats would be XML. The XML files can then be requested directly from IGSDB by a simple https get request with the [locator](https://github.com/ise621/building-envelope-data/blob/7706287bb6035eb31536c09b65b917d1025bedb0/apis/database.graphql#L1565) of the resource.

**Comment by christoph-maurer** [comment]
If you don't agree that this issue was solved, please reopen it!
