### ISSUE TITLE
How to interpret a "numberWithUncertainty" with no "uncertainty" or "confidenceInterval"?

### ISSUE THREAD

**Issue by StephenCzarnecki** [ise621/building-envelope-data#185]
We are wondering how that is interpreted because we are wondering how our measured values should be represented.  We currently do not have any information about uncertainty.

In https://github.com/ise621/building-envelope-data/blob/develop/tests/valid/opticalData/tree.json there is a transmittance value with an "uncertainValue" but no "uncertainty" or "confidenceInterval"

That transmittance value is defined as being a "numberWithUncertainty"

"numberWithUncertainty" is define in https://github.com/ise621/building-envelope-data/blob/develop/schemas/number.json as having one of two representations. 
- Just a number which means "If the value is 100% certain, then this this option is used."
- An object with a required "uncertainValue" and optional "uncertainty" and "confidenceInterval"

So it seems that if we just provide a number that is claiming we have 100% confidence in the value.  Which is not the case.  We know that there is some uncertainty in the measurements but do not currently have any information about what that may be.

In general we suspect that we should either return all values as just a number or all values as "uncertainValue" with no other information.  But we wanted to check what is the meaning of "uncertainValue" with no other information or if you had any other guidance or suggestions on how to represent the measured values.

**Comment by christoph-maurer** [comment]
You are right suspecting that you should either return al values just as a number or all values as "uncertainValue" with no other information. I recommend the second option because it allows to add an uncertainty when it becomes available. The first option can be used for example when a manufacturer guarantees 2 years of warranty. Then the number 2 is 100% certain. I can currently not imagine optical values which are 100% certain.

**Comment by christoph-maurer** [comment]
We are currently rethinking the definition of numbersWithUncertainty in #194 in order to make the data less verbose.

**Comment by christoph-maurer** [comment]
With #195, we have [redefined numbers with uncertainty](https://github.com/ise621/building-envelope-data/blob/f7480ab62efb3a44e0a5ccddd5fd8ebe0793c894/schemas/number.json#L24) to make the JSON data less verbose. "uncertainValue" is now only used for values which have a defined "uncertainty" and "confidenceInterval". A mere number means that the uncertainty is unknown. 

The current answer to @StephenCzarnecki 's question is therefore: There is no "uncertainValue" without defined "uncertainty" and "confidenceInterval". If a numberWithUncertainty is only a value, then this means that the uncertainty of this value is unknown.

Thank you, @StephenCzarnecki for the initiative to rethink the schema of "numberWithUncertainty"!
