### ISSUE TITLE
IGSDB glazing records URL

### ISSUE THREAD

**Issue by StephenCzarnecki** [ise621/building-envelope-data#220]
This url will return a summary view of all the glazing products (i.e. not shading and not shade materials) in the IGSDB

```
https://igsdb.lbl.gov/api/v1/products/?type=glazing
```

A quick example using python and requests may help

```python
import requests
import json

igsdb_api_token = "INSERT_YOUR_TOKEN_HERE"  
url_all_products = "https://igsdb.lbl.gov/api/v1/products?type=glazing"
headers = {"Authorization": "Token {token}".format(token=igsdb_api_token)}  # Token authorization headers
all_products_response = requests.get(url_all_products, headers=headers)
all_products = json.loads(all_products_response.content)
for product in all_products:
	print("IGSDB product_id: {id}, Product Name: {name}, Manufacturer: {manufacturer}".format(id=product["product_id"], name=product["name"], manufacturer=["manufacturer"]))
```

IGSDB only the IGSDB product_id as the id for the record in the existing REST API.  And the information returned by the above is only a summary.  I've included a couple other fields that may help you decide what products to use for the minimum viable product and demos.  More are available in the summary if needed.

Also to get the complete set of information about any record using the existing REST API you can use

```
https://igsdb.lbl.gov/api/v1/products/{product_id}
```

e.g. to get all the information for generic clear 3mm glass:

```
https://igsdb.lbl.gov/api/v1/products/363 
```

Let us know if you would like any assistance with any of the above or need any other information from IGSDB.

**Comment by christoph-maurer** [comment]
Thank you for this clear presentation, @StephenCzarnecki ! URLs like 
`
https://igsdb.lbl.gov/api/v1/products/363
`
will work fine for Phase I of the minimum viable product. @simon-wacker and me will let you know if any question should pop up.
