### ISSUE TITLE
Why is GetHttpsResourceTree defined as interface in database.graphql?  

### ISSUE THREAD

**Issue by StephenCzarnecki** [ise621/building-envelope-data#225]
In database.graphql the GetHttpsResourceTree is defined as an interface but there does not seem to be anything in the schema that implements the interface.

When attempting to use Ariadne to create an object to handle GetHttpsResourceTree it throws an error that GetHttpsResourceTree is an instance of GraphQLInterfaceType and expects a GraphQLObjectType.  This error is resolved if I change the definition in database.graphql from ```interface GetHttpsResourceTree``` to ```type GetHttpsResourceTree```

This https://graphql.org/learn/schema/ and this https://graphql-ruby.org/type_definitions/interfaces seem to indicate that interfaces are purely abstract and that types are needed to implement them but I am not sure if that is generally true or not.

So I'm not sure if this is a quirk of ariadne or if it is pointing out something that should be changed in database.graphql.  If it is correct to call GetHttpsResourceTree an interface let me know.

**Comment by christoph-maurer** [comment]
@StephenCzarnecki I think you are right that we should change `interface GetHttpsResourceTree` to `type GetHttpsResourceTree`. Do you agree, @simon-wacker ?

**Comment by simon-wacker** [comment]
Yes, it should be an object type and it is now https://github.com/ise621/building-envelope-data/commit/b07b8bf2c585b9abbc8a31c2a03d23756dd3c2e2
