### ISSUE TITLE
Allow users to decide how to filter lists: by all values, no values, or some values

### ISSUE THREAD

**Issue by simon-wacker** [ise621/building-envelope-data#261]
If a property is a list of values, then the corresponding proposition has the properties `all`, `none`, and `some`, each having a proposition type corresponding to the type of values in the list. For example, the proposition property `nearnormalHemisphericalVisibleTransmittance` corresponding to the value property `nearnormalHemisphericalVisibleTransmittances` [was renamed to `nearnormalHemisphericalVisibleTransmittances`](https://github.com/ise621/building-envelope-data/pull/260/commits/24949aa8576753fa8c721ffadb1389e7c7ccbfe5#diff-e13d8bcd03e0c0deaf5320874c7a021bd04181ea32c24a6862ecbe6fd36f6032L598) and given the type [`FloatsPropositionInput`](https://github.com/ise621/building-envelope-data/pull/260/commits/24949aa8576753fa8c721ffadb1389e7c7ccbfe5#diff-e13d8bcd03e0c0deaf5320874c7a021bd04181ea32c24a6862ecbe6fd36f6032R541) (note the plural), with the properties `all`, `none`, and `some` of type `FloatPropositionInput`.

For query examples with `uValues` and `gValues` see [`allData.graphql`](https://github.com/ise621/building-envelope-data/blob/26cb5e257ee79d119a473c7f0a59e5bb4887cd8a/queries/database/allData.graphql) and for all changes to the GraphQL schema see https://github.com/ise621/building-envelope-data/pull/260/commits/24949aa8576753fa8c721ffadb1389e7c7ccbfe5 and https://github.com/ise621/building-envelope-data/commit/26cb5e257ee79d119a473c7f0a59e5bb4887cd8a

Note also that the parameter [`where` for `all*Data` and `has*Data` queries is now optional](https://github.com/ise621/building-envelope-data/pull/260/commits/22a229c13e6b636b449e1640cb61d80322032ded).

Can these changes be incorporated into the LBNL implementation of the GraphQL API?

**Comment by christoph-maurer** [comment]
@StephenCzarnecki says that he has solved this topic with his commit. @simon-wacker do you agree?

**Comment by simon-wacker** [comment]
Yes, the changes are in the latest schema and I did some manual tests that worked fine. Thanks for your work!
