### ISSUE TITLE
When vscode or ajv support draft2019-09, then update

### ISSUE THREAD

**Issue by simon-wacker** [ise621/building-envelope-data#32]
As soon as either Visual Studio Code or ajv-cli supports JSON Schema Draft 2019-09, then please exchange `"$schema": "http://json-schema.org/draft-07/schema"` by `"$schema": "https://json-schema.org/draft/2019-09/schema"` in the schemas.

* AJV [received grants to implement support for Draft 2019-09](https://www.poberezkin.com/posts/2020-08-14-ajv-json-validator-mozilla-open-source-grant-openjs-foundation.html).
* Visual Studio Code developers [think about support for Draft 2019-09](https://github.com/microsoft/vscode/issues/98724#issuecomment-681835734) but [have not started development yet](https://github.com/microsoft/vscode-json-languageservice/issues/71#issuecomment-681837123).

**Comment by cmbankester** [comment]
It appears that [ajv-cli](https://github.com/ajv-validator/ajv-cli) supports draft 2019-09 as of ajv version 7
