### ISSUE TITLE
Create BIPVT examples

### ISSUE THREAD

**Issue by simon-wacker** [ise621/building-envelope-data#37]
In GitLab by @christoph-maurer on Jul 22, 2020, 15:35

As discussed with Wendelin via Slack on 22.7.20.

**Comment by christoph-maurer** [comment]
@JohannesEisenlohr Can you please combine the examples for [BIST](https://github.com/ise621/building-envelope-data/blob/combine-multiple-ways-to-specify-directions/examples/dbe/calorimetric/bistMeasurement.json) and [BIPV](https://github.com/ise621/building-envelope-data/blob/combine-multiple-ways-to-specify-directions/examples/dbe/photovoltaic/bipvModuleBuildingNatIse.json) to a simple example of BIPVT?
